config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :users
  end
  post 'create_user' => 'admin/users#create', as: :create_user
  
  resources :profile
  
  get 'timesheet/previous' => 'timesheet#previous', as: :timesheet_previous
  get 'timesheet/:date' => 'timesheet#show', as: :timesheet_show
  resources :timesheet
  get 'timesheet/:id/starttime' => 'timesheet#starttime', as: :timesheet_starttime
  get 'timesheet/:id/finishshift' => 'timesheet#finishshift', as: :timesheet_finishshift
  get 'timesheet/:id/reopenshift' => 'timesheet#reopenshift', as: :timesheet_reopenshift

  resources :breaks
  post 'breaks/:id/finish' => 'breaks#finish', as: :break_finish

  get 'home/index'

  root 'home#index'

end

app/models/timesheet.rb
class Timesheet < ActiveRecord::Base
	belongs_to :user
	has_many :breaks

	def latest_break
		self.breaks.last
	end
	
	def has_active_break?
		abreak = latest_break
		
		abreak ? abreak.currently_active? : false
	end
	
	def to_param
		for_date.strftime("%Y-%m-%d")
	end
end

app/controllers/timesheet_controller.rb
class TimesheetController < ApplicationController
	before_filter :authenticate_user!
	before_filter :load_timesheet
	before_filter :load_previous_timesheet, :only => [:show]
	before_filter :load_breaks, :only => [:index]
	load_and_authorize_resource
	
	def update
		@timesheet.start_time = Time.parse(starttime_params[:start_time])
		@timesheet.save!
		redirect_to timesheet_index_path
	end
	
	def index
		@totaltime = Time.diff(@timesheet.finish_time || DateTime.current, @timesheet.start_time, "%s")[:diff].to_i
	end
	
	def finishshift
		@timesheet.finish_time = DateTime.current
		@timesheet.save
		redirect_to timesheet_index_path
	end
	
	def reopenshift
		@timesheet.finish_time = nil
		@timesheet.save
		redirect_to timesheet_index_path
	end
	
	def previous
		@timesheets = current_user.timesheets.where.not(:finish_time => nil).paginate(:page => params[:page], :per_page => 14).order('id DESC')
	end
	
	protected
	
	def load_timesheet
		@timesheet = current_user.timesheets.find_by for_date: params[:id] || Date.today
	end
	
	def load_breaks
		@breaks = @timesheet.breaks.where(["break_type=?", 1])
		@lunches = @timesheet.breaks.where(["break_type=?", 2])
	end

	def starttime_params
		params.require(:timesheet).permit(:start_time)
	end
	
	def load_previous_timesheet
		@timesheet = current_user.timesheets.find_by for_date: params[:date]
		@totaltime = Time.diff(@timesheet.finish_time, @timesheet.start_time, "%s")[:diff].to_i
		@breaks = @timesheet.breaks.where(["break_type=?", 1])
		@lunches = @timesheet.breaks.where(["break_type=?", 2])
	end
end

app/helpers/timesheet_helper.rb
module TimesheetHelper
end

app/views/timesheet/index.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Timesheet for <%= text_date(@timesheet.for_date) %></h3>
	</div>

	<div class="panel-body">
 		<p>Your total time at work is: <%= format_time_duration_in_words(@totaltime) %></p>
		<div class="form-horizontal col-md-8">
			<div class="form-group">
				<div class="col-sm-2">
					Start time
				</div>
				<div class="col-sm-4">
					<%= format_time(@timesheet.start_time) %>
				</div>
				<div class="col-sm-2">
					<%= link_to('Edit Start Time', timesheet_starttime_path(@timesheet), class: "btn btn-info btn-xs") if @timesheet.finish_time == nil %>
				</div>
			</div>


			<div class="form-group">
				<div class="col-sm-2">
					Finish time
				</div>
				<div class="col-sm-4">
					<%= @timesheet.finish_time ? format_time(@timesheet.finish_time) : "" %>
				</div>
				<div class="col-sm-2">
<% if @timesheet.finish_time == nil -%>
					<%= link_to('Finish Shift', timesheet_finishshift_path(@timesheet), data: { confirm: 'Are you sure you have finished your shift?' }, class: "btn btn-danger btn-xs")  %>
<% else -%>
					<%= link_to('Reopen Shift', timesheet_reopenshift_path(@timesheet), data: { confirm: 'Are you sure you have reopen your shift?' }, class: "btn btn-danger btn-xs")  %>
<% end -%>
				</div>
			</div>

			<div class="form-group">
				<div class="col-sm-2">
					Breaks taken
				</div>
				<div class="col-sm-4">
					<%= @breaks.count > 0 ? "#{@breaks.count} (#{format_time_duration(@breaks.sum(:duration))} in total)" : "None" %>
				</div>
				<div class="col-sm-2">
					<%= link_to('Take a Break', breaks_path(:break_type => "1"), :method => :post, class: "btn btn-warning btn-xs") if @timesheet.finish_time == nil %>
				</div>
			</div>
<% if @breaks.count > 0 -%>
			<div class="form-group">
				<div class="col-sm-1">
				</div>
				<div class="col-sm-2">
					Break start
				</div>
				<div class="col-sm-2">
					Break end
				</div>
				<div class="col-sm-2">
					Duration
				</div>
			</div>
<% @breaks.each do |b| %>
			<div class="form-group">
				<div class="col-sm-1">
				</div>
				<div class="col-sm-2">
					<%= format_time_seconds(b.start_time) %>
				</div>
				<div class="col-sm-2">
					<%= format_time_seconds(b.finish_time) %>
				</div>
				<div class="col-sm-2">
					<%= format_time_duration(b.duration) %>
				</div>
			</div>
<% end %>
<% end -%>
			<div class="form-group">
				<div class="col-sm-2">
					Lunches taken
				</div>
				<div class="col-sm-4">
					<%= @lunches.count > 0 ? "#{@lunches.count} (#{format_time_duration(@lunches.sum(:duration))} in total)" : "None" %>
				</div>
				<div class="col-sm-2">
					<%= link_to('Go on Lunch', breaks_path(:break_type => "2"), :method => :post, class: "btn btn-warning btn-xs") if @timesheet.finish_time == nil %>
				</div>
			</div>
<% if @lunches.count > 0 -%>
			<div class="form-group">
				<div class="col-sm-1">
				</div>
				<div class="col-sm-2">
					Lunch start
				</div>
				<div class="col-sm-2">
					Lunch end
				</div>
				<div class="col-sm-2">
					Duration
				</div>
			</div>
<% @lunches.each do |b| %>
			<div class="form-group">
				<div class="col-sm-1">
				</div>
				<div class="col-sm-2">
					<%= format_time_seconds(b.start_time) %>
				</div>
				<div class="col-sm-2">
					<%= format_time_seconds(b.finish_time) %>
				</div>
				<div class="col-sm-2">
					<%= format_time_duration(b.duration) %>
				</div>
			</div>
<% end %>
<% end -%>
		</div>
	</div>
</div>
<% if current_user.has_previous_timesheets? -%>
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Previous Timesheets</h3>
	</div>
	<div class="panel-body">
		<p>You have <%= pluralize(current_user.timesheets.count(:all) - 1, "previous timesheet") %> on record.</p>
		<p><%= link_to "Click here to view your previous timesheets", timesheet_previous_path %>.</p>
	</div>
</div>
<% end -%>

app/views/timesheet/previous.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Here are your previous timesheets</h3>
	</div>

    <div class="panel-body">
        <div class="form-horizontal col-md-8">
<% @timesheets.each do |timesheet| -%>
            <div class="form-group">
				<div class="col-sm-4">
				    <%= link_to text_date(timesheet.for_date), timesheet_show_path(timesheet) %>
				</div>
			</div>
<% end -%>
        <div class="pagination">
            <%= will_paginate @timesheets, renderer: BootstrapPagination::Rails %>
        </div>
    </div>
</div>

app/views/timesheet/show.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Timesheet for <%= text_date(@timesheet.for_date) %></h3>
	</div>

	<div class="panel-body">
 		<p>Total work time: <%= format_time_duration_in_words(@totaltime) %></p>
		<div class="form-horizontal col-md-8">
			<div class="form-group">
				<div class="col-sm-2">
					Start time
				</div>
				<div class="col-sm-4">
					<%= format_time(@timesheet.start_time) %>
				</div>
			</div>


			<div class="form-group">
				<div class="col-sm-2">
					Finish time
				</div>
				<div class="col-sm-4">
					<%= @timesheet.finish_time ? format_time(@timesheet.finish_time) : "" %>
				</div>
			</div>

			<div class="form-group">
				<div class="col-sm-2">
					Breaks taken
				</div>
				<div class="col-sm-4">
					<%= @breaks.count > 0 ? "#{@breaks.count} (#{format_time_duration(@breaks.sum(:duration))} in total)" : "None" %>
				</div>
			</div>
<% if @breaks.count > 0 -%>
			<div class="form-group">
				<div class="col-sm-1">
				</div>
				<div class="col-sm-2">
					Break start
				</div>
				<div class="col-sm-2">
					Break end
				</div>
				<div class="col-sm-2">
					Duration
				</div>
			</div>
<% @breaks.each do |b| %>
			<div class="form-group">
				<div class="col-sm-1">
				</div>
				<div class="col-sm-2">
					<%= format_time_seconds(b.start_time) %>
				</div>
				<div class="col-sm-2">
					<%= format_time_seconds(b.finish_time) %>
				</div>
				<div class="col-sm-2">
					<%= format_time_duration(b.duration) %>
				</div>
			</div>
<% end %>
<% end -%>
			<div class="form-group">
				<div class="col-sm-2">
					Lunches taken
				</div>
				<div class="col-sm-4">
					<%= @lunches.count > 0 ? "#{@lunches.count} (#{format_time_duration(@lunches.sum(:duration))} in total)" : "None" %>
				</div>
			</div>
<% if @lunches.count > 0 -%>
			<div class="form-group">
				<div class="col-sm-1">
				</div>
				<div class="col-sm-2">
					Lunch start
				</div>
				<div class="col-sm-2">
					Lunch end
				</div>
				<div class="col-sm-2">
					Duration
				</div>
			</div>
<% @lunches.each do |b| %>
			<div class="form-group">
				<div class="col-sm-1">
				</div>
				<div class="col-sm-2">
					<%= format_time_seconds(b.start_time) %>
				</div>
				<div class="col-sm-2">
					<%= format_time_seconds(b.finish_time) %>
				</div>
				<div class="col-sm-2">
					<%= format_time_duration(b.duration) %>
				</div>
			</div>
<% end %>
<% end -%>
		</div>
	</div>
</div>

app/views/timesheet/starttime.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Your start time for <%= text_date(@timesheet.for_date) %></h3>
	</div>

	<div class="panel-body">
		<p>If you need to edit your start time (if you forgot to login when you started work, or you logged in some time before you started) then you can edit the hour and minutes below (seconds do not matter).</p>
		<div class="form-horizontal col-md-8">
			<%= form_for(@timesheet, html: {class: "form-horizontal col-md-8"}) do |f| %>
				<div class="form-group">
					<div class="col-sm-8">
						<p>Current start time: <%= format_time(@timesheet.start_time) %></p>
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-4">
						<label class="control-label">New start time</label>
				        <%= f.time_field :start_time, value: get_time(@timesheet.start_time).strftime("%H:%M"), autofocus: true, class: "form-control" %>
					</div>
				</div>
				
				<div class="form-group">
					<%= f.submit "Update", class: "btn btn-primary" %>
					<%= link_to "Cancel", timesheet_index_path, class: "btn btn-warning" %>
				</div>
			<% end %>
		</div>
	</div>
</div>