config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :users
  end
  post 'create_user' => 'admin/users#create', as: :create_user
  
  resources :profile
  
  get 'timesheet/previous' => 'timesheet#previous', as: :timesheet_previous
  get 'timesheet/:date' => 'timesheet#show', as: :timesheet_show
  resources :timesheet
  get 'timesheet/:id/starttime' => 'timesheet#starttime', as: :timesheet_starttime
  get 'timesheet/:id/finishshift' => 'timesheet#finishshift', as: :timesheet_finishshift
  get 'timesheet/:id/reopenshift' => 'timesheet#reopenshift', as: :timesheet_reopenshift

  resources :breaks
  post 'breaks/:id/finish' => 'breaks#finish', as: :break_finish

  get 'home/index'

  root 'home#index'

end

app/views/partials/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">BT Liveperson</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<% if current_user.admin? -%>
        <li><%= link_to "Admin", admin_users_path %></li>
<% end -%>
        <li><%= link_to "My Timesheet", timesheet_index_path %></li>
        <li><a href="#">Dispositions</a></li>
        <li><a href="#">Personal Canned Responses</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <p class="navbar-text">Logged in as: <%= link_to current_user.name, edit_user_registration_path, class: "edit-profile" %>.</p>
        <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
      </ul>
    </div><!--/.navbar-collapse -->
  </div>
</nav>