config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :users
  end
  post 'create_user' => 'admin/users#create', as: :create_user
  
  resources :profile
  
  get 'timesheet/previous' => 'timesheet#previous', as: :timesheet_previous
  get 'timesheet/:date' => 'timesheet#show', as: :timesheet_show
  resources :timesheet
  get 'timesheet/:id/starttime' => 'timesheet#starttime', as: :timesheet_starttime
  get 'timesheet/:id/finishshift' => 'timesheet#finishshift', as: :timesheet_finishshift
  get 'timesheet/:id/reopenshift' => 'timesheet#reopenshift', as: :timesheet_reopenshift

  resources :breaks
  post 'breaks/:id/finish' => 'breaks#finish', as: :break_finish

  get 'home/index'

  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable, :trackable, :timeoutable
  belongs_to :role
  has_many :timesheets
  
  def admin?
    self.role.name == "Admin"
  end
  
  def email_required?
    false
  end
  
  def active_timesheet
    timesheet = self.timesheets.find_by for_date: Date.today
    
    if timesheet == nil
      previous_timesheet = self.timesheets.last
      if previous_timesheet != nil
        Rails.logger.debug previous_timesheet.id
        previous_timesheet.finish_time = previous_timesheet.start_time.in_time_zone("London").end_of_day if previous_timesheet.finish_time == nil
        previous_timesheet.save
      end
      
      
			timesheet = Timesheet.new
			timesheet.user_id = self.id
			timesheet.for_date = Date.today
			timesheet.start_time = self.current_sign_in_at.to_date == Date.today ? self.current_sign_in_at : DateTime.current
			timesheet.save
		end
		
		timesheet
  end
  
  def has_previous_timesheets?
    self.timesheets.count(:all) > 1
  end
  
  validates :login, :name, :role_id, presence: true
  validates :login, uniqueness: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
	load_and_authorize_resource

	# GET /users
	# GET /users.json
	def index
		#@users = User.all
	end
	
	# GET /users/1
	# GET /users/1.json
	def show
	end
	
	# GET /users/new
	def new
		#@user = User.new
	end
	
	# GET /users/1/edit
	def edit
	end
	
	# POST /users
	# POST /users.json
	def create
		#@user = User.new(user_params)
		
		respond_to do |format|
			if @user.save
				Rails.logger.debug "It saved"
				format.html { redirect_to admin_users_url, notice: 'User was successfully created.' }
				format.json { render :show, status: :created, location: @user }
			else
				Rails.logger.debug "It didn't save"
				format.html { render :new }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end
	
	# PATCH/PUT /users/1
	# PATCH/PUT /users/1.json
	def update
		if params[:user][:password].blank?
			params[:user].delete("password")
			params[:user].delete("password_confirmation")
		end
		
		respond_to do |format|
			if @user.update(user_params)
				format.html { redirect_to admin_users_url, notice: 'User was successfully updated.' }
				format.json { render :show, status: :ok, location: @user }
			else
				format.html { render :edit }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end
	
	# DELETE /users/1
	# DELETE /users/1.json
	def destroy
		@user.destroy
		respond_to do |format|
			format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
			format.json { head :no_content }
		end
	end
	
	private
	# Use callbacks to share common setup or constraints between actions.
	def set_user
		@user = User.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def user_params
		params.require(:user).permit(:login, :email, :lp_name, :password, :password_confirmation, :name, :role_id, :changepassword)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <span class="btn-group pull-right">
      <%= link_to 'New User', new_user_path, class: "btn btn-primary" %>
    </span>
    <h3 class="panel-title">Listing Users</h3>
    
  </div>
  
  

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Role</th>
        <th>Last logged in at</th>
        <th>Delete</th>
      </tr>
    </thead>
  
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.name, edit_user_path(user) %></td>
          <td><%= user.role.name %></td>
          <td><%= user.last_sign_in_at %></td>
          <td><%= link_to '<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>'.html_safe, user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/users/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Create a new user</h3>
  </div>
  <div class="panel-body">
    <%= form_for(resource, as: resource_name, url: create_user_path, html: {class: "form-horizontal col-md-8"}) do |f| %>
      <%= devise_error_messages! %>
      
      <div class="form-group">
        <label class="col-sm-2 control-label">Username</label>
        <div class="col-sm-6">
          <%= f.text_field :login, autofocus: true, class: "form-control" %>
        </div>
      </div>
      
      <div class="form-group">
        <label class="col-sm-2 control-label">Full name</label>
        <div class="col-sm-6">
          <%= f.text_field :name, autofocus: true, class: "form-control" %>
        </div>
      </div>
    
      <div class="form-group">
        <%= f.label :password, class: "col-sm-2 control-label" %>
        <div class="col-sm-6">
          <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :role, class: "col-sm-2 control-label" %>
        <div class="col-sm-6">
          <%= collection_select(:user, :role_id, Role.all, :id, :name, {prompt: true}, class: "form-control")  %>
        </div>
      </div>
    
      <div class="form-group">
          <%= f.submit "Create user", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>